apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: ci-push
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: ci-push
      eventSourceName: ci
      eventName: example
      # filters:
      #   data:
      #     - path: body.X-GitHub-Event
      #       value:
      #         - push
      #       type: string
      #     - path: body.ref
      #       comparator: '='
      #       template: '{{ trimPrefix "refs/heads/" .Input }}'
      #       type: string
      #       value:
      #         - main
      #     - path: body.deleted
      #       type: bool
      #       value:
      #         - 'false'
      #     - path: body.ref
      #       template: '{{ (split "/" .Input)._1 }}'
      #       value:
      #         - heads
      #       type: string
  triggers:
    - template:
        conditions: "ci-push"
        name: github-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-build-
              spec:
                workflowTemplateRef:
                  name: ci
                arguments:
                  parameters:
                  - name: GIT_REPO
                  - name: GIT_REVISION
                  - name: PR_NUMBER
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: ci-push
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: ci-push
                dataKey: body.pull_request.number
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: ci-push
                dataKey: body.pull_request.number
