apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: ci
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    example:
      repositories:
        - owner: MosenzonTal
          names:
            - host-ip-app
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: https://ea54-147-235-196-17.eu.ngrok.io
      events:
        - pull_request
      apiToken:
        name: github-access
        key: token
      insecure: false
      active: true
      contentType: json
      deleteHookOnFinish: true

      